import requests
from bs4 import BeautifulSoup
urlArr = ['https://lms.synergy.ru/course/c_8220908/megacampus/mUqRRMdvc8'
          '/Kuetee3bdX.html',
          'https://lms.synergy.ru/course/c_8220911/megacampus/qk76aaXvzI'
          '/hpUVLY5xn5.html',
          'https://lms.synergy.ru/course/c_8220912/megacampus/JUeKiEE0NA'
          '/ueY2ao72GD.html',
          'https://lms.synergy.ru/course/c_8220913/megacampus/lEqpWwnXVp'
          '/GBG8JN3uVt.html',
          'https://lms.synergy.ru/course/c_8220914/megacampus/74h8yfxLnr'
          '/AvDleA6WbO.html',
          'https://lms.synergy.ru/course/c_8220915/megacampus/jIDuv0HBys'
          '/Wphi2V9Nhn.html',
          'https://lms.synergy.ru/course/c_8220916/megacampus/0nkqzwD3re'
          '/5re6V2jhZJ.html',
          'https://lms.synergy.ru/course/c_8220917/megacampus/M4cA3OP8Y2'
          '/iqJ6uBMYmx.html',
          'https://lms.synergy.ru/course/c_8220920/megacampus/nEOzEOoE3M'
          '/XmCUsZUgsz.html',
          'https://lms.synergy.ru/course/c_8220921/megacampus/RovNtJvYGv'
          '/5r9o6pbeXi.html',
          'https://lms.synergy.ru/course/c_8220922/megacampus/ly9tBxmW6E'
          '/zYpsrp77za.html',
          'https://lms.synergy.ru/course/c_8220923/megacampus/qddMe7KpYT'
          '/rdbIxjHXRy.html',
          'https://lms.synergy.ru/course/c_8220924/megacampus/izUMFWo79M'
          '/1OA9B70Tc6.html',
          'https://lms.synergy.ru/course/c_8220925/megacampus/GFRE1tUxDL'
          '/G2h35BIK6d.html',
          'https://lms.synergy.ru/course/c_8220926/megacampus/ORxT5ig0NB'
          '/dKRuKxbSDx.html',
          'https://lms.synergy.ru/course/c_8220927/megacampus/MTijbyiaHf'
          '/3MZ9h5QxxX.html',
          'https://lms.synergy.ru/course/c_8220928/megacampus/C4Y8oigf6B'
          '/grb1Z9xvQc.html',
          'https://lms.synergy.ru/course/c_8220929/megacampus/neT3Eji77u'
          '/aHCIAQjv4g.html',
          'https://lms.synergy.ru/course/c_8818912/megacampus/Iw5EXGLa5f'
          '/gbBlO94LqS.html',
          'https://lms.synergy.ru/course/c_8818913/megacampus/UbquwMGqej'
          '/MypMH4IXP5.html',
          'https://lms.synergy.ru/course/c_8818914/megacampus/4qHUuTZCL5'
          '/60ThikvXug.html',
          'https://lms.synergy.ru/course/c_8818915/megacampus/0oWqExQimB'
          '/kZoKcK9OlU.html',
          'https://lms.synergy.ru/course/c_8818916/megacampus/tswxNt43qz'
          '/jGs9737sEy.html',
          'https://lms.synergy.ru/course/c_8818917/megacampus/HLHlgJ7bKL'
          '/Zs83MJI3dG.html',
          'https://lms.synergy.ru/course/c_8818918/megacampus/6MHgEjI6Gh'
          '/475lTRRXv0.html',
          'https://lms.synergy.ru/course/c_8818919/megacampus/AtjKFHjYPx'
          '/Sh7ZsuOohy.html',
          'https://lms.synergy.ru/course/c_8818920/megacampus/mhxJcdudEB'
          '/0ih1J90nDI.html',
          'https://lms.synergy.ru/course/c_8979097/megacampus/ngXwpaOIhH'
          '/tdbxNZ5sQY.html',
          'https://lms.synergy.ru/course/c_8979138/megacampus/XRmm5UZabT'
          '/n4Fk6XSiwv.html',
          'https://lms.synergy.ru/course/c_8979140/megacampus/M4TRRkV5Fb'
          '/Pw1um9exNh.html',
          'https://lms.synergy.ru/course/c_8979141/megacampus/mBlfKrL0Sc'
          '/PRQqo9dzNx.html',
          'https://lms.synergy.ru/course/c_8979149/megacampus/bIbX1A1GMO'
          '/JXLeds5WVk.html',
          'https://lms.synergy.ru/course/c_8979142/megacampus/xn7tzI0gYh'
          '/BUOSx2ZL2M.html',
          'https://lms.synergy.ru/course/c_8979154/megacampus/pmEHlilxLo'
          '/zbsnXtby6I.html',
          'https://lms.synergy.ru/course/c_8979155/megacampus/1OsTl3h6wy'
          '/5BYGa01dhM.html',
          'https://lms.synergy.ru/course/c_8979178/megacampus/WeqZ3pRSF6'
          '/s8gu91h5Kk.html',
          'https://lms.synergy.ru/course/c_8979179/megacampus/vS74yXnHpE'
          '/AyxfTh4jwq.html',
          'https://lms.synergy.ru/course/c_8979180/megacampus/L4ntHzND91'
          '/gGMaISsDg5.html',
          'https://lms.synergy.ru/course/c_8979570/megacampus/R3nRokFytb'
          '/7nbOdVByaS.html',
          'https://lms.synergy.ru/course/c_8979583/megacampus/nabLYeaTi4'
          '/yxmAxHKV1H.html',
          'https://lms.synergy.ru/course/c_8979584/megacampus/vulCNit9qv'
          '/fUgXIxtpei.html',
          'https://lms.synergy.ru/course/c_8979585/megacampus/3Hq30sRXRO'
          '/5gOiy9void.html',
          'https://lms.synergy.ru/course/c_8979607/megacampus/c4gUsMfoYd'
          '/1t9Vjdi1uG.html',
          'https://lms.synergy.ru/course/c_8979608/megacampus/rl1CroiGWQ'
          '/wnMFv19b4p.html',
          'https://lms.synergy.ru/course/c_8979620/megacampus/u4lGcT6Fwz'
          '/qizcvgEAtX.html',
          'https://lms.synergy.ru/course/c_8979621/megacampus/1uUEyvuEwI'
          '/TGAEIBsAcv.html',
          'https://lms.synergy.ru/course/c_8979622/megacampus/oNsXujTM98'
          '/XMm6IjkVSq.html',
          'https://lms.synergy.ru/course/c_8979633/megacampus/342MTBBc88'
          '/BcczlsoKTE.html',
          'https://lms.synergy.ru/course/c_8979634/megacampus/znFQZiFcjp'
          '/a0JgC2hJUL.html',
          'https://lms.synergy.ru/course/c_8979647/megacampus/fOkuarpHkR'
          '/IW6TpLYTtN.html',
          'https://lms.synergy.ru/course/c_8979648/megacampus/kWmzMd6dvR'
          '/LCCfAoGZp1.html',
          'https://lms.synergy.ru/course/c_8979649/megacampus/2KLz0kUc6G'
          '/txD1ppxErg.html',
          'https://lms.synergy.ru/course/c_8979659/megacampus/sH18nEPg1e'
          '/5ur0BAoK17.html',
          'https://lms.synergy.ru/course/c_8979662/megacampus/DgocEmYbok/gRQcTqD2vB.html']
for i in urlArr:
    sourse = requests.get(i).text
    soup = BeautifulSoup(sourse, 'html.parser')
    print(soup.prettify())
# print(type(urlArr), len(urlArr))
